TOPIC_KEYWORDS: dict[str, list[str]] = {
    "tahara": ["طہارت", "پاکی", "نجاست", "tahara", "paki", "najasat", "napaki"],
    "wuzu": ["وضو", "wuzu", "wudu", "ablution"],
    "ghusl": ["غسل", "ghusl", "ghusal", "نہانا"],
    "tayammum": ["تیمم", "tayammum", "مٹی"],
    "haiz": ["حیض", "haiz", "ایام", "periods", "mahwari", "ماہواری"],
    "nifas": ["نفاس", "nifas", "nifaas", "زچگی"],
    "istihaza": ["استحاضہ", "istihaza", "istehaza"],
    "salah": ["نماز", "صلوۃ", "namaz", "salah", "salat", "رکعت"],
    "sawm": ["روزہ", "صوم", "roza", "sawm", "fasting", "افطار", "سحری"],
    "zakat": ["زکوۃ", "zakat", "صدقہ", "عشر"],
    "hajj": ["حج", "hajj", "عمرہ", "umrah", "طواف", "tawaf"],
    "nikah": ["نکاح", "nikah", "شادی", "zawaj", "marriage"],
    "talaq": ["طلاق", "talaq", "خلع", "عدت", "iddat"],
    "trade": ["تجارت", "بیع", "خرید", "فروخت", "سود", "riba"],
    "food": ["کھانا", "حلال", "حرام", "halal", "haram", "ذبیحہ"],
    "dress": ["لباس", "پردہ", "ستر", "pardah", "satr"],
    "masjid": ["مسجد", "masjid", "جامع"],
    "janaza": ["جنازہ", "janaza", "دفن", "تدفین", "کفن"],
    "quran": ["قرآن", "تلاوت", "quran", "tilawat"],
    "dua": ["دعا", "وظیفہ", "dua", "wazifa", "ذکر", "dhikr"],
}
