// Ramadan content data — wazaif, dhikr lists, daily surahs

export const wazaifData = [
  { day: 1, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Ya Raheemu', count: '133 times' },
    { namaz: 'Zohar', wazifa: 'Ya Kareemu', count: '133 times' },
    { namaz: 'Asar', wazifa: 'Ya Razzaqu', count: '200 times' },
    { namaz: 'Magrib', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Isha', wazifa: 'Surah Aale Imran (Ayat 26)', count: '33 times' },
  ]},
  { day: 2, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: '5th Kalma', count: '70 times' },
    { namaz: 'Zohar', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Asar', wazifa: 'Durood-e-Ibrahim', count: '25 times' },
    { namaz: 'Magrib', wazifa: 'Ya Wahhabu', count: '133 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh (4 Rakat)', count: '' },
  ]},
  { day: 3, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Ya Haafizu', count: '111 times' },
    { namaz: 'Zohar', wazifa: 'Ya Naasiru', count: '222 times' },
    { namaz: 'Asar', wazifa: 'Ya Baasitu', count: '111 times' },
    { namaz: 'Magrib', wazifa: 'Ayatul Kursi', count: '25 times' },
    { namaz: 'Isha', wazifa: 'Dua-e-Karb', count: '25 times' },
  ]},
  { day: 4, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Zohar', wazifa: 'Ya Hayyu Ya Qayyum', count: '133 times' },
    { namaz: 'Asar', wazifa: 'Dua-e-Jamila', count: '3 times' },
    { namaz: 'Magrib', wazifa: 'Surah Wattin', count: '11 times' },
    { namaz: 'Isha', wazifa: 'Surah Muzammil', count: '3 times' },
  ]},
  { day: 5, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Asmaul Husna', count: '3 times' },
    { namaz: 'Zohar', wazifa: 'Dua-e-Karb', count: '17 times' },
    { namaz: 'Asar', wazifa: 'Surah Mulk', count: '2 times' },
    { namaz: 'Magrib', wazifa: 'Astagfar', count: '200 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh (4 Rakat)', count: '' },
  ]},
  { day: 6, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Aale Imran (Ayat 26)', count: '21 times' },
    { namaz: 'Zohar', wazifa: 'Dua-e-Rizq', count: '17 times' },
    { namaz: 'Asar', wazifa: 'Surah Talaq (Ayat 3)', count: '17 times' },
    { namaz: 'Magrib', wazifa: 'Ayatul Kursi', count: '25 times' },
    { namaz: 'Isha', wazifa: 'Dua-e-Rizq', count: '50 times' },
  ]},
  { day: 7, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Ya Kareemu', count: '200 times' },
    { namaz: 'Zohar', wazifa: '5th Kalma', count: '33 times' },
    { namaz: 'Asar', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Magrib', wazifa: '3rd Kalma', count: '70 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh (4 Rakat)', count: '' },
  ]},
  { day: 8, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Fatah', count: '1 time' },
    { namaz: 'Zohar', wazifa: 'Dua-e-Rizq', count: '25 times' },
    { namaz: 'Asar', wazifa: '5th Kalma', count: '100 times' },
    { namaz: 'Magrib', wazifa: 'Dua-e-Rizq', count: '25 times' },
    { namaz: 'Isha', wazifa: 'Surah Aale Imran (Ayat 26)', count: '70 times' },
  ]},
  { day: 9, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Tauba (Last 2 Ayat)', count: '11 times' },
    { namaz: 'Zohar', wazifa: 'Surah Baqrah (1st Ruku)', count: '11 times' },
    { namaz: 'Asar', wazifa: 'Surah Aale Imran (Ayat 26)', count: '17 times' },
    { namaz: 'Magrib', wazifa: 'Surah Baqrah (Last Ruku)', count: '11 times' },
    { namaz: 'Isha', wazifa: 'Salatul Hajaat (4 Rakat)', count: '' },
  ]},
  { day: 10, ashra: 1, dua: { ar: 'رَبِّ اغْفِرْ وَارْحَمْ وَأَنْتَ خَيْرُ الرَّاحِمِينَ', ru: 'Rabbighfir Warham Wa Anta Khayrur Rahimeen', ur: 'اے میرے رب! مجھے بخش دے، مجھ پر رحم فرما، تو سب سے بہتر رحم کرنے والا ہے۔' }, schedule: [
    { namaz: 'Fajr', wazifa: '5th Kalma', count: '70 times' },
    { namaz: 'Zohar', wazifa: 'Dua-e-Karb', count: '17 times' },
    { namaz: 'Asar', wazifa: 'Dua-e-Jamila', count: '3 times' },
    { namaz: 'Magrib', wazifa: 'Dua-e-Najat', count: '40 times' },
    { namaz: 'Isha', wazifa: 'Surah Yaseen', count: '1 time' },
  ]},
  { day: 11, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Fatiha', count: '12 times' },
    { namaz: 'Zohar', wazifa: 'Surah Fatah', count: '1 time' },
    { namaz: 'Asar', wazifa: 'Ayatul Kursi', count: '17 times' },
    { namaz: 'Magrib', wazifa: 'Durood Shareef', count: '55 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh (4 Rakat)', count: '' },
  ]},
  { day: 12, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Dua-e-Rizq', count: '40 times' },
    { namaz: 'Zohar', wazifa: 'Surah Baqrah (1st Ruku)', count: '11 times' },
    { namaz: 'Asar', wazifa: 'Durood-e-Ibrahim', count: '47 times' },
    { namaz: 'Magrib', wazifa: 'Surah Baqrah (Last 2 Ayat)', count: '11 times' },
    { namaz: 'Isha', wazifa: 'Dua-e-Karb', count: '40 times' },
  ]},
  { day: 13, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Jumuah (Ayat 4)', count: '40 times' },
    { namaz: 'Zohar', wazifa: 'Surah Falaq', count: '47 times' },
    { namaz: 'Asar', wazifa: 'Surah Naas', count: '47 times' },
    { namaz: 'Magrib', wazifa: 'Dua-e-Najat', count: '11 times' },
    { namaz: 'Isha', wazifa: 'Salatul Hajaat (4 Rakat) + Surah Muzammil', count: '' },
  ]},
  { day: 14, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Tauba (Last 2 Ayat)', count: '21 times' },
    { namaz: 'Zohar', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Asar', wazifa: 'Dua-e-Karb', count: '25 times' },
    { namaz: 'Magrib', wazifa: 'Astagfirullah', count: '100 times' },
    { namaz: 'Isha', wazifa: '20 Rakat Nafl (Bataure Shukrana)', count: '' },
  ]},
  { day: 15, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Fatah', count: '3 times' },
    { namaz: 'Zohar', wazifa: 'Salatul Hajaat (4 Rakat)', count: '' },
    { namaz: 'Asar', wazifa: 'Durood Shareef', count: '55 times' },
    { namaz: 'Magrib', wazifa: 'Dua-e-Karb', count: '17 times' },
    { namaz: 'Isha', wazifa: 'Surah Aale Imran (Ayat 26)', count: '40 times' },
  ]},
  { day: 16, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Fatiha', count: '47 times' },
    { namaz: 'Zohar', wazifa: 'Ayatul Kursi', count: '11 times' },
    { namaz: 'Asar', wazifa: 'Ya Hayyu Ya Qayyum', count: '100 times' },
    { namaz: 'Magrib', wazifa: 'Durood-e-Ibrahim', count: '25 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh + 7 Salam', count: '11 times' },
  ]},
  { day: 17, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Muzammil', count: '2 times' },
    { namaz: 'Zohar', wazifa: 'Surah Fatiha', count: '40 times' },
    { namaz: 'Asar', wazifa: 'Dua-e-Magfirat', count: '25 times' },
    { namaz: 'Magrib', wazifa: 'Astagfar', count: '47 times' },
    { namaz: 'Isha', wazifa: 'Surah Fatah', count: '1 time' },
  ]},
  { day: 18, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Tauba (Last 2 Ayat)', count: '21 times' },
    { namaz: 'Zohar', wazifa: 'Surah Jumuah (Ayat 4)', count: '40 times' },
    { namaz: 'Asar', wazifa: 'Surah Talaq (Ayat 3)', count: '25 times' },
    { namaz: 'Magrib', wazifa: 'Dua-e-Karb', count: '21 times' },
    { namaz: 'Isha', wazifa: 'Surah Yaseen', count: '1 time' },
  ]},
  { day: 19, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Surah Jumuah (Ayat 4)', count: '40 times' },
    { namaz: 'Zohar', wazifa: 'Surah Aale Imran (Ayat 26)', count: '33 times' },
    { namaz: 'Asar', wazifa: 'Durood Shareef', count: '55 times' },
    { namaz: 'Magrib', wazifa: 'Surah Baqrah (Last Ruku)', count: '11 times' },
    { namaz: 'Isha', wazifa: 'Salatul Tasbeeh (4 Rakat)', count: '' },
  ]},
  { day: 20, ashra: 2, dua: { ar: 'أَسْتَغْفِرُ اللّٰهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَّأَتُوبُ إِلَيْهِ', ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa Atubu Ilayh', ur: 'میں اللہ سے اپنے تمام گناہوں کی بخشش مانگتا ہوں جو میرا رب ہے اور اسی کی طرف رجوع کرتا ہوں۔' }, schedule: [
    { namaz: 'Fajr', wazifa: 'Astagfar', count: '70 times' },
    { namaz: 'Zohar', wazifa: '7 Salam', count: '17 times' },
    { namaz: 'Asar', wazifa: 'Ayatul Kursi', count: '27 times' },
    { namaz: 'Magrib', wazifa: 'Durood-e-Ibrahim', count: '33 times' },
    { namaz: 'Isha', wazifa: 'Salatul Hajaat (4 Rakat) + 200x Astagfar', count: '' },
  ]},
];

export const dhikr3Times = [
  { ru: 'Ayatul Kursi', en: 'Ayatul Kursi', ur: 'آيَةُ الْكُرْسِيِّ' },
  { ru: 'Surah Falaq, Naas, Ikhlaas', en: 'Surah Falaq, Naas, Ikhlaas', ur: 'سُوْرَةُ الْفَلَقِ، النَّاسِ، الْإِخْلَاصِ' },
  { ru: 'Bismillahi Ala Deeni Bismillahi Ala Nafsi Wa Wuldi Wa Ahli Wa Maali', en: 'Bismillahi Ala Deeni Bismillahi Ala Nafsi Wa Wuldi Wa Ahli Wa Maali', ur: 'بِسْمِ اللّٰهِ عَلٰى دِيْنِيْ، بِسْمِ اللّٰهِ عَلٰى نَفْسِيْ وَوُلْدِيْ وَأَهْلِيْ وَمَالِيْ' },
  { ru: 'Raditu Billahi Rabbaw Wabil Islami Deenaw Wabi Muhammadin Nabiyya', en: 'Raditu Billahi Rabbaw Wabil Islami Deenaw Wabi Muhammadin Nabiyya', ur: 'رَضِيْتُ بِاللّٰهِ رَبًّا وَّبِالْإِسْلَامِ دِيْنًا وَّبِمُحَمَّدٍ نَبِيًّا' },
  { ru: 'Bismillahil Lazi La Yadurru Ma-Asmihi Shayun Fil Ardi Wala Fis Samaie Wahuwas Samiul Aleem', en: 'Bismillahil Lazi La Yadurru Ma-Asmihi Shayun Fil Ardi Wala Fis Samaie Wahuwas Samiul Aleem', ur: 'بِسْمِ اللّٰهِ الَّذِيْ لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيْعُ الْعَلِيْمُ' },
  { ru: 'Durood-e-Ibrahim', en: 'Durood-e-Ibrahim', ur: 'دُرُوْدِ إِبْرَاهِيْمِ' },
  { ru: 'Durood-e-Taaj', en: 'Durood-e-Taaj', ur: 'دُرُوْدِ تَاج' },
  { ru: 'Astagfirullaha Waatubu Ilayh', en: 'Astagfirullaha Waatubu Ilayh', ur: 'أَسْتَغْفِرُ اللّٰهَ وَأَتُوْبُ إِلَيْهِ' },
  { ru: 'Sallallahu Ala Muhammad Sallallahu Alayhi Wasallam', en: 'Sallallahu Ala Muhammad Sallallahu Alayhi Wasallam', ur: 'صَلَّى اللّٰهُ عَلٰى مُحَمَّدٍ صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ' },
  { ru: 'SubhanAllahi Wabihamdihi SubhanAllahil Azeem', en: 'SubhanAllahi Wabihamdihi SubhanAllahil Azeem', ur: 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ سُبْحَانَ اللّٰهِ الْعَظِيْمِ' },
  { ru: 'La Hawla Wala Quwwata Illa Billahil Aliyyil Azeem', en: 'La Hawla Wala Quwwata Illa Billahil Aliyyil Azeem', ur: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ الْعَلِيِّ الْعَظِيْمِ' },
];

export const dhikr100Times = [
  { ru: 'SubhanAllah', en: 'SubhanAllah', ur: 'سُبْحَانَ اللّٰهِ' },
  { ru: 'Alhamdulillah', en: 'Alhamdulillah', ur: 'اَلْحَمْدُ لِلّٰهِ' },
  { ru: 'Allahu Akbar', en: 'Allahu Akbar', ur: 'اَللّٰهُ أَكْبَرُ' },
  { ru: 'La Ilaha Illallahu Muhammadur Rasulullahi \uFDFA', en: 'La Ilaha Illallahu Muhammadur Rasulullahi \uFDFA', ur: 'لَا إِلٰهَ إِلَّا اللّٰهُ مُحَمَّدٌ رَّسُوْلُ اللّٰهِ ﷺ' },
  { ru: 'La Ilaha Illa Anta Subhanaka Inni Kuntu Minaz Zaalimeen', en: 'La Ilaha Illa Anta Subhanaka Inni Kuntu Minaz Zaalimeen', ur: 'لَا إِلٰهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّيْ كُنْتُ مِنَ الظَّالِمِيْنَ' },
  { ru: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa-atubu Ilayh', en: 'Astagfirullaha Rabbi Min Kulli Zambiw Wa-atubu Ilayh', ur: 'أَسْتَغْفِرُ اللّٰهَ رَبِّيْ مِنْ كُلِّ ذَنْبٍ وَّأَتُوْبُ إِلَيْهِ' },
  { ru: 'Allahumma Innaka Afuwwun Tuhibbul Afwa Fa-afu Anni', en: 'Allahumma Innaka Afuwwun Tuhibbul Afwa Fa-afu Anni', ur: 'اَللّٰهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّيْ' },
  { ru: 'JazAllahu Anna Muhammadan Maa Huwa Ahluhu', en: 'JazAllahu Anna Muhammadan Maa Huwa Ahluhu', ur: 'جَزَى اللّٰهُ عَنَّا مُحَمَّدًا مَا هُوَ أَهْلُهُ' },
  { ru: 'SubhanAllahi Wabi Hamdihi SubhanAllahil Azeem', en: 'SubhanAllahi Wabi Hamdihi SubhanAllahil Azeem', ur: 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ سُبْحَانَ اللّٰهِ الْعَظِيْمِ' },
  { ru: 'La Hawla Wala Quwwata Illa Billahil Aliyyil Azeem', en: 'La Hawla Wala Quwwata Illa Billahil Aliyyil Azeem', ur: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ الْعَلِيِّ الْعَظِيْمِ' },
  { ru: 'Allahumma Ajirna Minan Naar', en: 'Allahumma Ajirna Minan Naar', ur: 'اَللّٰهُمَّ أَجِرْنَا مِنَ النَّارِ' },
  { ru: 'La Ilaha Illallahu Wahdahu La Sharika Lahu, Lahul Mulku Walahul Hamdu Wahuwa Ala Kulli Shayin Qadir', en: 'La Ilaha Illallahu Wahdahu La Sharika Lahu, Lahul Mulku Walahul Hamdu Wahuwa Ala Kulli Shayin Qadir', ur: 'لَا إِلٰهَ إِلَّا اللّٰهُ وَحْدَهُ لَا شَرِيْكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلٰى كُلِّ شَيْءٍ قَدِيْرٌ' },
  { ru: 'Ya Hayyu Ya Qayyumu Birahmatika Astagisu', en: 'Ya Hayyu Ya Qayyumu Birahmatika Astagisu', ur: 'يَا حَيُّ يَا قَيُّوْمُ بِرَحْمَتِكَ أَسْتَغِيْثُ' },
  { ru: 'SubhanAllahi Wa Bihamdihi Adada Khalqihi Wa Rida Nafsihi Wa Zinata Arshihi Wa Midada Kalimatih', en: 'SubhanAllahi Wa Bihamdihi Adada Khalqihi Wa Rida Nafsihi Wa Zinata Arshihi Wa Midada Kalimatih', ur: 'سُبْحَانَ اللّٰهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ وَرِضَا نَفْسِهِ وَزِيْنَةَ عَرْشِهِ وَمِدَادَ كَلِمَاتِهِ' },
  { ru: 'Hasbiyallahu La Ilaha Illa Huwa Alayhi Tawaqaltu Wa Huwa Rabbul Arshil Azeem', en: 'Hasbiyallahu La Ilaha Illa Huwa Alayhi Tawaqaltu Wa Huwa Rabbul Arshil Azeem', ur: 'حَسْبِيَ اللّٰهُ لَا إِلٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيْمِ' },
  { ru: 'Astagfirullahallazi La Ilaha Illa Huwal Hayyul Qayyumu Wa Atubu Ilayh', en: 'Astagfirullahallazi La Ilaha Illa Huwal Hayyul Qayyumu Wa Atubu Ilayh', ur: 'أَسْتَغْفِرُ اللّٰهَ الَّذِيْ لَا إِلٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّوْمُ وَأَتُوْبُ إِلَيْهِ' },
  { ru: 'Allahumma Inni Asaluka Ilman Nafia Wa Rizqan Tayyiba Wa Amalam Mutaqabbala', en: 'Allahumma Inni Asaluka Ilman Nafia Wa Rizqan Tayyiba Wa Amalam Mutaqabbala', ur: 'اَللّٰهُمَّ إِنِّيْ أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُّتَقَبَّلًا' },
  { ru: 'Sallallahu Alayhi Wasallam', en: 'Sallallahu Alayhi Wasallam', ur: 'صَلَّى اللّٰهُ عَلَيْهِ وَسَلَّمَ' },
];

export const dailySurahs = [
  { ru: 'Surah Yaseen', en: 'Surah Yaseen', ur: 'سُوْرَةُ يٰسٓ' },
  { ru: 'Surah Fatah', en: 'Surah Fatah', ur: 'سُوْرَةُ الْفَتْحِ' },
  { ru: 'Surah Rahman', en: 'Surah Rahman', ur: 'سُوْرَةُ الرَّحْمٰنِ' },
  { ru: 'Surah Muzzammil', en: 'Surah Muzzammil', ur: 'سُوْرَةُ الْمُزَّمِّلِ' },
  { ru: 'Surah Waqiah', en: 'Surah Waqiah', ur: 'سُوْرَةُ الْوَاقِعَةِ' },
  { ru: 'Surah Mulk', en: 'Surah Mulk', ur: 'سُوْرَةُ الْمُلْكِ' },
  { ru: 'Surah Sajdah', en: 'Surah Sajdah', ur: 'سُوْرَةُ السَّجْدَةِ' },
  { ru: 'Surah Dukhan', en: 'Surah Dukhan', ur: 'سُوْرَةُ الدُّخَانِ' },
  { ru: 'Surah Ikhlaas', en: 'Surah Ikhlaas', ur: 'سُوْرَةُ الْإِخْلَاصِ' },
  { ru: 'Surah Falaq', en: 'Surah Falaq', ur: 'سُوْرَةُ الْفَلَقِ' },
  { ru: 'Surah Naas', en: 'Surah Naas', ur: 'سُوْرَةُ النَّاسِ' },
  { ru: 'Surah Baqrah (complete in 1-2 days)', en: 'Surah Baqrah (complete in 1-2 days)', ur: 'سُوْرَةُ الْبَقَرَةِ (۱-۲ دن میں مکمل)' },
  { ru: '1 Para daily (compulsory)', en: '1 Para daily (compulsory)', ur: 'روزانہ ۱ پارہ (لازمی)' },
];
